MOOD_SONGS = {
    "happy": [
        {"name": "Happy", "artist": "Pharrell Williams"},
        {"name": "Can't Stop the Feeling", "artist": "Justin Timberlake"},
        {"name": "Good as Hell", "artist": "Lizzo"},
        {"name": "Walking on Sunshine", "artist": "Katrina and the Waves"},
        {"name": "Best Day of My Life", "artist": "American Authors"},
        {"name": "I Gotta Feeling", "artist": "The Black Eyed Peas"},
        {"name": "Shake It Off", "artist": "Taylor Swift"},
        {"name": "Don't Stop Me Now", "artist": "Queen"},
        {"name": "Lovely Day", "artist": "Bill Withers"},
        {"name": "Here Comes the Sun", "artist": "The Beatles"},
    ],
    "sad": [
        {"name": "Someone Like You", "artist": "Adele"},
        {"name": "Fix You", "artist": "Coldplay"},
        {"name": "Skinny Love", "artist": "Bon Iver"},
        {"name": "The Night We Met", "artist": "Lord Huron"},
        {"name": "All I Want", "artist": "Kodaline"},
        {"name": "When the Party's Over", "artist": "Billie Eilish"},
        {"name": "Driver's License", "artist": "Olivia Rodrigo"},
        {"name": "Hurt", "artist": "Johnny Cash"},
        {"name": "Let Her Go", "artist": "Passenger"},
        {"name": "Mad World", "artist": "Gary Jules"},
    ],
    "heartbroken": [
        {"name": "All I Want", "artist": "Kodaline"},
        {"name": "The Night We Met", "artist": "Lord Huron"},
        {"name": "Wrecking Ball", "artist": "Miley Cyrus"},
        {"name": "Jar of Hearts", "artist": "Christina Perri"},
        {"name": "Stay With Me", "artist": "Sam Smith"},
        {"name": "Chasing Cars", "artist": "Snow Patrol"},
        {"name": "Turning Tables", "artist": "Adele"},
        {"name": "Cry Me a River", "artist": "Justin Timberlake"},
        {"name": "White Flag", "artist": "Dido"},
        {"name": "Somebody That I Used to Know", "artist": "Gotye"},
    ],
    "romantic": [
        {"name": "Perfect", "artist": "Ed Sheeran"},
        {"name": "All of Me", "artist": "John Legend"},
        {"name": "Thinking Out Loud", "artist": "Ed Sheeran"},
        {"name": "A Thousand Years", "artist": "Christina Perri"},
        {"name": "Can't Help Falling in Love", "artist": "Elvis Presley"},
        {"name": "At Last", "artist": "Etta James"},
        {"name": "Make You Feel My Love", "artist": "Adele"},
        {"name": "La Vie En Rose", "artist": "Edith Piaf"},
        {"name": "From the Start", "artist": "Laufey"},
        {"name": "Bloom", "artist": "The Paper Kites"},
    ],
    "flirty": [
        {"name": "Senorita", "artist": "Shawn Mendes ft. Camila Cabello"},
        {"name": "Slow Hands", "artist": "Niall Horan"},
        {"name": "Adore You", "artist": "Harry Styles"},
        {"name": "Versace on the Floor", "artist": "Bruno Mars"},
        {"name": "Temperature", "artist": "Sean Paul"},
        {"name": "Crazy in Love", "artist": "Beyonce"},
        {"name": "Love Me Like You Do", "artist": "Ellie Goulding"},
        {"name": "Boyfriend", "artist": "Selena Gomez"},
        {"name": "Earned It", "artist": "The Weeknd"},
        {"name": "Hey Ya", "artist": "OutKast"},
    ],
    "nostalgic": [
        {"name": "Summer of 69", "artist": "Bryan Adams"},
        {"name": "Don't You Forget About Me", "artist": "Simple Minds"},
        {"name": "Take On Me", "artist": "a-ha"},
        {"name": "Africa", "artist": "Toto"},
        {"name": "Bohemian Rhapsody", "artist": "Queen"},
        {"name": "Hotel California", "artist": "Eagles"},
        {"name": "Piano Man", "artist": "Billy Joel"},
        {"name": "Sweet Child O Mine", "artist": "Guns N Roses"},
        {"name": "Come On Eileen", "artist": "Dexys Midnight Runners"},
        {"name": "Girls Just Want to Have Fun", "artist": "Cyndi Lauper"},
    ],
    "dreamy": [
        {"name": "Electric Feel", "artist": "MGMT"},
        {"name": "Midnight City", "artist": "M83"},
        {"name": "Space Song", "artist": "Beach House"},
        {"name": "Dreams", "artist": "Fleetwood Mac"},
        {"name": "Holocene", "artist": "Bon Iver"},
        {"name": "Pink Moon", "artist": "Nick Drake"},
        {"name": "Cornelia Street", "artist": "Taylor Swift"},
        {"name": "Lover", "artist": "Taylor Swift"},
        {"name": "Cherry Wine", "artist": "Hozier"},
        {"name": "Myth", "artist": "Beach House"},
    ],
    "chill": [
        {"name": "Banana Pancakes", "artist": "Jack Johnson"},
        {"name": "Better Together", "artist": "Jack Johnson"},
        {"name": "Sunflower", "artist": "Post Malone ft. Swae Lee"},
        {"name": "Good Days", "artist": "SZA"},
        {"name": "Sunday Morning", "artist": "Maroon 5"},
        {"name": "Snowfall", "artist": "Oneheart x reidenshi"},
        {"name": "Coffee", "artist": "beabadoobee"},
        {"name": "Retrograde", "artist": "James Blake"},
        {"name": "Intro", "artist": "The xx"},
        {"name": "Lazy Sunday", "artist": "Arctic Monkeys"},
    ],
    "peaceful": [
        {"name": "Clair de Lune", "artist": "Debussy"},
        {"name": "Weightless", "artist": "Marconi Union"},
        {"name": "River Flows in You", "artist": "Yiruma"},
        {"name": "Experience", "artist": "Ludovico Einaudi"},
        {"name": "Watermark", "artist": "Enya"},
        {"name": "Gymnopédie No. 1", "artist": "Erik Satie"},
        {"name": "Only Time", "artist": "Enya"},
        {"name": "Porcelain", "artist": "Moby"},
        {"name": "Orinoco Flow", "artist": "Enya"},
        {"name": "Breathe", "artist": "Pink Floyd"},
    ],
    "emotional": [
        {"name": "Someone Like You", "artist": "Adele"},
        {"name": "Fix You", "artist": "Coldplay"},
        {"name": "Iris", "artist": "Goo Goo Dolls"},
        {"name": "Hallelujah", "artist": "Jeff Buckley"},
        {"name": "The Night We Met", "artist": "Lord Huron"},
        {"name": "Chasing Cars", "artist": "Snow Patrol"},
        {"name": "When We Were Young", "artist": "Adele"},
        {"name": "Driver's License", "artist": "Olivia Rodrigo"},
        {"name": "Exile", "artist": "Taylor Swift ft. Bon Iver"},
        {"name": "The Scientist", "artist": "Coldplay"},
    ],
    "bittersweet": [
        {"name": "Fast Car", "artist": "Tracy Chapman"},
        {"name": "Landslide", "artist": "Fleetwood Mac"},
        {"name": "Let Her Go", "artist": "Passenger"},
        {"name": "Photograph", "artist": "Ed Sheeran"},
        {"name": "When We Were Young", "artist": "Adele"},
        {"name": "Vienna", "artist": "Billy Joel"},
        {"name": "Cats in the Cradle", "artist": "Harry Chapin"},
        {"name": "Dreams", "artist": "Fleetwood Mac"},
        {"name": "Exile", "artist": "Taylor Swift ft. Bon Iver"},
        {"name": "The Night We Met", "artist": "Lord Huron"},
    ],
    "hopeful": [
        {"name": "Rise Up", "artist": "Andra Day"},
        {"name": "A Sky Full of Stars", "artist": "Coldplay"},
        {"name": "Brave", "artist": "Sara Bareilles"},
        {"name": "Fight Song", "artist": "Rachel Platten"},
        {"name": "Hall of Fame", "artist": "The Script ft. Will.I.Am"},
        {"name": "Believer", "artist": "Imagine Dragons"},
        {"name": "Dog Days Are Over", "artist": "Florence and the Machine"},
        {"name": "Good Life", "artist": "OneRepublic"},
        {"name": "Don't Stop Believin", "artist": "Journey"},
        {"name": "Try", "artist": "Pink"},
    ],
    "healing": [
        {"name": "Clean", "artist": "Taylor Swift"},
        {"name": "Breathe Me", "artist": "Sia"},
        {"name": "Rise Up", "artist": "Andra Day"},
        {"name": "Fix You", "artist": "Coldplay"},
        {"name": "Let It Be", "artist": "The Beatles"},
        {"name": "Lean on Me", "artist": "Bill Withers"},
        {"name": "Bridge Over Troubled Water", "artist": "Simon and Garfunkel"},
        {"name": "You Are Not Alone", "artist": "Michael Jackson"},
        {"name": "Better in Time", "artist": "Leona Lewis"},
        {"name": "Glorious", "artist": "Macklemore ft. Skylar Grey"},
    ],
    "motivational": [
        {"name": "Lose Yourself", "artist": "Eminem"},
        {"name": "Till I Collapse", "artist": "Eminem"},
        {"name": "Hall of Fame", "artist": "The Script ft. Will.I.Am"},
        {"name": "Believer", "artist": "Imagine Dragons"},
        {"name": "Eye of the Tiger", "artist": "Survivor"},
        {"name": "We Will Rock You", "artist": "Queen"},
        {"name": "Can't Hold Us", "artist": "Macklemore ft. Ryan Lewis"},
        {"name": "Not Afraid", "artist": "Eminem"},
        {"name": "Thunder", "artist": "Imagine Dragons"},
        {"name": "Stronger", "artist": "Kanye West"},
    ],
    "confident": [
        {"name": "Good as Hell", "artist": "Lizzo"},
        {"name": "Juice", "artist": "Lizzo"},
        {"name": "Truth Hurts", "artist": "Lizzo"},
        {"name": "Born This Way", "artist": "Lady Gaga"},
        {"name": "Roar", "artist": "Katy Perry"},
        {"name": "Confident", "artist": "Demi Lovato"},
        {"name": "7 Rings", "artist": "Ariana Grande"},
        {"name": "Thank U Next", "artist": "Ariana Grande"},
        {"name": "God Is a Woman", "artist": "Ariana Grande"},
        {"name": "Run the World", "artist": "Beyonce"},
    ],
    "powerful": [
        {"name": "Power", "artist": "Kanye West"},
        {"name": "HUMBLE", "artist": "Kendrick Lamar"},
        {"name": "DNA", "artist": "Kendrick Lamar"},
        {"name": "Black Skinhead", "artist": "Kanye West"},
        {"name": "Run the World", "artist": "Beyonce"},
        {"name": "Flawless", "artist": "Beyonce"},
        {"name": "Monster", "artist": "Kanye West ft. Jay-Z"},
        {"name": "No Church in the Wild", "artist": "Jay-Z ft. Kanye West"},
        {"name": "Unstoppable", "artist": "Sia"},
        {"name": "Fighter", "artist": "Christina Aguilera"},
    ],
    "hype": [
        {"name": "Sicko Mode", "artist": "Travis Scott"},
        {"name": "HUMBLE", "artist": "Kendrick Lamar"},
        {"name": "God's Plan", "artist": "Drake"},
        {"name": "Bad and Boujee", "artist": "Migos ft. Lil Uzi Vert"},
        {"name": "Rockstar", "artist": "Post Malone ft. 21 Savage"},
        {"name": "Mask Off", "artist": "Future"},
        {"name": "Power", "artist": "Kanye West"},
        {"name": "Jumpman", "artist": "Drake ft. Future"},
        {"name": "Turn Down for What", "artist": "DJ Snake ft. Lil Jon"},
        {"name": "Started From the Bottom", "artist": "Drake"},
    ],
    "party": [
        {"name": "Levitating", "artist": "Dua Lipa"},
        {"name": "Don't Start Now", "artist": "Dua Lipa"},
        {"name": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars"},
        {"name": "September", "artist": "Earth Wind and Fire"},
        {"name": "Get Lucky", "artist": "Daft Punk ft. Pharrell Williams"},
        {"name": "Blinding Lights", "artist": "The Weeknd"},
        {"name": "Can't Stop the Feeling", "artist": "Justin Timberlake"},
        {"name": "Party Rock Anthem", "artist": "LMFAO"},
        {"name": "I Gotta Feeling", "artist": "The Black Eyed Peas"},
        {"name": "Timber", "artist": "Pitbull ft. Kesha"},
    ],
    "energetic": [
        {"name": "Lose Yourself", "artist": "Eminem"},
        {"name": "Thunderstruck", "artist": "AC/DC"},
        {"name": "Jump Around", "artist": "House of Pain"},
        {"name": "Pump It", "artist": "The Black Eyed Peas"},
        {"name": "Till I Collapse", "artist": "Eminem"},
        {"name": "Legends Never Die", "artist": "Against the Current"},
        {"name": "Run the World", "artist": "Beyonce"},
        {"name": "Unstoppable", "artist": "Sia"},
        {"name": "Stronger", "artist": "Kanye West"},
        {"name": "Power", "artist": "Kanye West"},
    ],
    "aggressive": [
        {"name": "Break Stuff", "artist": "Limp Bizkit"},
        {"name": "Killing in the Name", "artist": "Rage Against the Machine"},
        {"name": "Bodies", "artist": "Drowning Pool"},
        {"name": "Faint", "artist": "Linkin Park"},
        {"name": "Given Up", "artist": "Linkin Park"},
        {"name": "Down with the Sickness", "artist": "Disturbed"},
        {"name": "Chop Suey", "artist": "System of a Down"},
        {"name": "Toxicity", "artist": "System of a Down"},
        {"name": "Last Resort", "artist": "Papa Roach"},
        {"name": "Freak on a Leash", "artist": "Korn"},
    ],
    "angry": [
        {"name": "Numb", "artist": "Linkin Park"},
        {"name": "In the End", "artist": "Linkin Park"},
        {"name": "Crawling", "artist": "Linkin Park"},
        {"name": "Boulevard of Broken Dreams", "artist": "Green Day"},
        {"name": "American Idiot", "artist": "Green Day"},
        {"name": "Smells Like Teen Spirit", "artist": "Nirvana"},
        {"name": "Paint It Black", "artist": "The Rolling Stones"},
        {"name": "Bulls on Parade", "artist": "Rage Against the Machine"},
        {"name": "Walk", "artist": "Pantera"},
        {"name": "Psychosocial", "artist": "Slipknot"},
    ],
    "dark": [
        {"name": "Comfortably Numb", "artist": "Pink Floyd"},
        {"name": "Black Hole Sun", "artist": "Soundgarden"},
        {"name": "Fade to Black", "artist": "Metallica"},
        {"name": "Welcome to the Black Parade", "artist": "My Chemical Romance"},
        {"name": "Paint It Black", "artist": "The Rolling Stones"},
        {"name": "Closer", "artist": "Nine Inch Nails"},
        {"name": "Bury a Friend", "artist": "Billie Eilish"},
        {"name": "Bad Guy", "artist": "Billie Eilish"},
        {"name": "Nightmare", "artist": "Avenged Sevenfold"},
        {"name": "November Rain", "artist": "Guns N Roses"},
    ],
    "mysterious": [
        {"name": "Teardrop", "artist": "Massive Attack"},
        {"name": "Unfinished Sympathy", "artist": "Massive Attack"},
        {"name": "Angel", "artist": "Massive Attack"},
        {"name": "Return to Innocence", "artist": "Enigma"},
        {"name": "Sadeness", "artist": "Enigma"},
        {"name": "Kashmir", "artist": "Led Zeppelin"},
        {"name": "In the Air Tonight", "artist": "Phil Collins"},
        {"name": "Thriller", "artist": "Michael Jackson"},
        {"name": "White Rabbit", "artist": "Jefferson Airplane"},
        {"name": "Orinoco Flow", "artist": "Enya"},
    ],
    "cinematic": [
        {"name": "Time", "artist": "Hans Zimmer"},
        {"name": "Interstellar Theme", "artist": "Hans Zimmer"},
        {"name": "Experience", "artist": "Ludovico Einaudi"},
        {"name": "Arrival of the Birds", "artist": "The Cinematic Orchestra"},
        {"name": "To Build a Home", "artist": "The Cinematic Orchestra"},
        {"name": "Nuvole Bianche", "artist": "Ludovico Einaudi"},
        {"name": "Comptine d Un Autre Ete", "artist": "Yann Tiersen"},
        {"name": "La Valse d Amelie", "artist": "Yann Tiersen"},
        {"name": "Now We Are Free", "artist": "Hans Zimmer"},
        {"name": "Ma Fleur", "artist": "The Cinematic Orchestra"},
    ],
    "ethereal": [
        {"name": "Cosmic Love", "artist": "Florence and the Machine"},
        {"name": "Dog Days Are Over", "artist": "Florence and the Machine"},
        {"name": "Midnight City", "artist": "M83"},
        {"name": "Outro", "artist": "M83"},
        {"name": "Space Song", "artist": "Beach House"},
        {"name": "Myth", "artist": "Beach House"},
        {"name": "Watermark", "artist": "Enya"},
        {"name": "May It Be", "artist": "Enya"},
        {"name": "Only Time", "artist": "Enya"},
        {"name": "A Sky Full of Stars", "artist": "Coldplay"},
    ],
    "playful": [
        {"name": "Dance Monkey", "artist": "Tones and I"},
        {"name": "Sugar", "artist": "Maroon 5"},
        {"name": "Cheap Thrills", "artist": "Sia"},
        {"name": "Dynamite", "artist": "BTS"},
        {"name": "Shut Up and Dance", "artist": "Walk the Moon"},
        {"name": "Tongue Tied", "artist": "Grouplove"},
        {"name": "Stolen Dance", "artist": "Milky Chance"},
        {"name": "Electric Feel", "artist": "MGMT"},
        {"name": "Kids", "artist": "MGMT"},
        {"name": "We Are Young", "artist": "Fun ft. Janelle Monae"},
    ],
    "epic": [
        {"name": "O Fortuna", "artist": "Carl Orff"},
        {"name": "Also Sprach Zarathustra", "artist": "Richard Strauss"},
        {"name": "Braveheart Theme", "artist": "James Horner"},
        {"name": "Gladiator Theme", "artist": "Hans Zimmer"},
        {"name": "Lord of the Rings Theme", "artist": "Howard Shore"},
        {"name": "Time", "artist": "Hans Zimmer"},
        {"name": "Interstellar Theme", "artist": "Hans Zimmer"},
        {"name": "We Will Rock You", "artist": "Queen"},
        {"name": "We Are the Champions", "artist": "Queen"},
        {"name": "Knights of Cydonia", "artist": "Muse"},
    ],
    "soulful": [
        {"name": "A Change Is Gonna Come", "artist": "Sam Cooke"},
        {"name": "Respect", "artist": "Aretha Franklin"},
        {"name": "Feeling Good", "artist": "Nina Simone"},
        {"name": "I Put a Spell on You", "artist": "Nina Simone"},
        {"name": "At Last", "artist": "Etta James"},
        {"name": "Try a Little Tenderness", "artist": "Otis Redding"},
        {"name": "Georgia on My Mind", "artist": "Ray Charles"},
        {"name": "What's Going On", "artist": "Marvin Gaye"},
        {"name": "Superstition", "artist": "Stevie Wonder"},
        {"name": "God Only Knows", "artist": "The Beach Boys"},
    ],
    "introspective": [
        {"name": "Holocene", "artist": "Bon Iver"},
        {"name": "Liability", "artist": "Lorde"},
        {"name": "Ribs", "artist": "Lorde"},
        {"name": "Supercut", "artist": "Lorde"},
        {"name": "Writer in the Dark", "artist": "Lorde"},
        {"name": "Hard Feelings", "artist": "Lorde"},
        {"name": "The Sound of Silence", "artist": "Simon and Garfunkel"},
        {"name": "Fast Car", "artist": "Tracy Chapman"},
        {"name": "Vienna", "artist": "Billy Joel"},
        {"name": "Blackbird", "artist": "The Beatles"},
    ],
    "lonely": [
        {"name": "Eleanor Rigby", "artist": "The Beatles"},
        {"name": "Sound of Silence", "artist": "Simon and Garfunkel"},
        {"name": "Lonely", "artist": "Akon"},
        {"name": "How to Save a Life", "artist": "The Fray"},
        {"name": "The Night We Met", "artist": "Lord Huron"},
        {"name": "Liability", "artist": "Lorde"},
        {"name": "Mr. Lonely", "artist": "Bobby Vinton"},
        {"name": "Mad World", "artist": "Gary Jules"},
        {"name": "I Am a Rock", "artist": "Simon and Garfunkel"},
        {"name": "Only the Lonely", "artist": "Roy Orbison"},
    ],
    "vulnerable": [
        {"name": "When the Party's Over", "artist": "Billie Eilish"},
        {"name": "Ocean Eyes", "artist": "Billie Eilish"},
        {"name": "idontwannabeyouanymore", "artist": "Billie Eilish"},
        {"name": "Liability", "artist": "Lorde"},
        {"name": "Breathe Me", "artist": "Sia"},
        {"name": "Heather", "artist": "Conan Gray"},
        {"name": "Skinny Love", "artist": "Bon Iver"},
        {"name": "Sober", "artist": "Demi Lovato"},
        {"name": "Clean", "artist": "Taylor Swift"},
        {"name": "From the Dining Table", "artist": "Harry Styles"},
    ],
    "yearning": [
        {"name": "Iris", "artist": "Goo Goo Dolls"},
        {"name": "Chasing Cars", "artist": "Snow Patrol"},
        {"name": "Say Something", "artist": "A Great Big World"},
        {"name": "All I Want", "artist": "Kodaline"},
        {"name": "Falling", "artist": "Harry Styles"},
        {"name": "Exile", "artist": "Taylor Swift ft. Bon Iver"},
        {"name": "Never Tear Us Apart", "artist": "INXS"},
        {"name": "Somebody That I Used to Know", "artist": "Gotye"},
        {"name": "The Night We Met", "artist": "Lord Huron"},
        {"name": "Skinny Love", "artist": "Bon Iver"},
    ],
    "melancholic": [
        {"name": "Holocene", "artist": "Bon Iver"},
        {"name": "Motion Picture Soundtrack", "artist": "Radiohead"},
        {"name": "The Scientist", "artist": "Coldplay"},
        {"name": "Mad World", "artist": "Gary Jules"},
        {"name": "Liability", "artist": "Lorde"},
        {"name": "Creep", "artist": "Radiohead"},
        {"name": "Hurt", "artist": "Nine Inch Nails"},
        {"name": "Black", "artist": "Pearl Jam"},
        {"name": "idontwannabeyouanymore", "artist": "Billie Eilish"},
        {"name": "How Soon Is Now", "artist": "The Smiths"},
    ],
    "rebellious": [
        {"name": "Killing in the Name", "artist": "Rage Against the Machine"},
        {"name": "Smells Like Teen Spirit", "artist": "Nirvana"},
        {"name": "American Idiot", "artist": "Green Day"},
        {"name": "Should I Stay or Should I Go", "artist": "The Clash"},
        {"name": "Anarchy in the UK", "artist": "Sex Pistols"},
        {"name": "Fight for Your Right", "artist": "Beastie Boys"},
        {"name": "Born to Run", "artist": "Bruce Springsteen"},
        {"name": "I Love Rock n Roll", "artist": "Joan Jett"},
        {"name": "Welcome to the Black Parade", "artist": "My Chemical Romance"},
        {"name": "Holiday", "artist": "Green Day"},
    ],
    "fearless": [
        {"name": "Fearless", "artist": "Taylor Swift"},
        {"name": "Brave", "artist": "Sara Bareilles"},
        {"name": "Unstoppable", "artist": "Sia"},
        {"name": "Stronger", "artist": "Kelly Clarkson"},
        {"name": "Run the World", "artist": "Beyonce"},
        {"name": "Fight Song", "artist": "Rachel Platten"},
        {"name": "Legends Never Die", "artist": "Against the Current"},
        {"name": "Kings and Queens", "artist": "Ava Max"},
        {"name": "Hall of Fame", "artist": "The Script ft. Will.I.Am"},
        {"name": "Eye of the Tiger", "artist": "Survivor"},
    ],
    "sensual": [
        {"name": "Earned It", "artist": "The Weeknd"},
        {"name": "Slow Motion", "artist": "Trey Songz"},
        {"name": "Motivation", "artist": "Normani"},
        {"name": "Body Party", "artist": "Ciara"},
        {"name": "Versace on the Floor", "artist": "Bruno Mars"},
        {"name": "Drunk in Love", "artist": "Beyonce"},
        {"name": "Climax", "artist": "Usher"},
        {"name": "Like I Do", "artist": "Jennifer Lopez"},
        {"name": "Skin", "artist": "Rihanna"},
        {"name": "No Scrubs", "artist": "TLC"},
    ],
    "cozy": [
        {"name": "Banana Pancakes", "artist": "Jack Johnson"},
        {"name": "Better Together", "artist": "Jack Johnson"},
        {"name": "Ho Hey", "artist": "The Lumineers"},
        {"name": "Home", "artist": "Edward Sharpe and the Magnetic Zeros"},
        {"name": "Sunday Morning", "artist": "Maroon 5"},
        {"name": "Golden Hour", "artist": "JVKE"},
        {"name": "Lover", "artist": "Taylor Swift"},
        {"name": "Sunday Best", "artist": "Surfaces"},
        {"name": "From the Start", "artist": "Laufey"},
        {"name": "Bloom", "artist": "The Paper Kites"},
    ],
    "warm": [
        {"name": "Golden Hour", "artist": "JVKE"},
        {"name": "Golden", "artist": "Harry Styles"},
        {"name": "Cardigan", "artist": "Taylor Swift"},
        {"name": "August", "artist": "Taylor Swift"},
        {"name": "Lover", "artist": "Taylor Swift"},
        {"name": "Sunday Best", "artist": "Surfaces"},
        {"name": "Feels Like Summer", "artist": "Weezer"},
        {"name": "Here Comes the Sun", "artist": "The Beatles"},
        {"name": "Lovely Day", "artist": "Bill Withers"},
        {"name": "You Are the Sunshine of My Life", "artist": "Stevie Wonder"},
    ],
    "summer": [
        {"name": "Watermelon Sugar", "artist": "Harry Styles"},
        {"name": "Summertime Magic", "artist": "Childish Gambino"},
        {"name": "Ocean", "artist": "Martin Garrix ft. Khalid"},
        {"name": "Summer", "artist": "Calvin Harris"},
        {"name": "Good Days", "artist": "SZA"},
        {"name": "Kokomo", "artist": "The Beach Boys"},
        {"name": "Good Vibrations", "artist": "The Beach Boys"},
        {"name": "Island in the Sun", "artist": "Weezer"},
        {"name": "Margaritaville", "artist": "Jimmy Buffett"},
        {"name": "Somewhere Over the Rainbow", "artist": "Israel Kamakawiwoole"},
    ],
    "late_night": [
        {"name": "Blinding Lights", "artist": "The Weeknd"},
        {"name": "After Hours", "artist": "The Weeknd"},
        {"name": "Midnight City", "artist": "M83"},
        {"name": "Starboy", "artist": "The Weeknd ft. Daft Punk"},
        {"name": "Save Your Tears", "artist": "The Weeknd"},
        {"name": "The Hills", "artist": "The Weeknd"},
        {"name": "Call Out My Name", "artist": "The Weeknd"},
        {"name": "Good Days", "artist": "SZA"},
        {"name": "Drew Barrymore", "artist": "SZA"},
        {"name": "3 AM", "artist": "Matchbox Twenty"},
    ],
    "roadtrip": [
        {"name": "Born to Run", "artist": "Bruce Springsteen"},
        {"name": "Take It Easy", "artist": "Eagles"},
        {"name": "Hotel California", "artist": "Eagles"},
        {"name": "Life Is a Highway", "artist": "Tom Cochrane"},
        {"name": "Fast Car", "artist": "Tracy Chapman"},
        {"name": "Africa", "artist": "Toto"},
        {"name": "American Pie", "artist": "Don McLean"},
        {"name": "Sweet Home Alabama", "artist": "Lynyrd Skynyrd"},
        {"name": "Mr. Jones", "artist": "Counting Crows"},
        {"name": "Ramblin Man", "artist": "Allman Brothers Band"},
    ],
    "rainy_day": [
        {"name": "November Rain", "artist": "Guns N Roses"},
        {"name": "Purple Rain", "artist": "Prince"},
        {"name": "Set Fire to the Rain", "artist": "Adele"},
        {"name": "Riders on the Storm", "artist": "The Doors"},
        {"name": "Only Happy When It Rains", "artist": "Garbage"},
        {"name": "No Rain", "artist": "Blind Melon"},
        {"name": "Rain", "artist": "The Beatles"},
        {"name": "Singing in the Rain", "artist": "Gene Kelly"},
        {"name": "The Rain Song", "artist": "Led Zeppelin"},
        {"name": "Blame It on the Rain", "artist": "Milli Vanilli"},
    ],
    "main_character": [
        {"name": "Unstoppable", "artist": "Sia"},
        {"name": "This Is Me", "artist": "Keala Settle"},
        {"name": "Brave", "artist": "Sara Bareilles"},
        {"name": "Roar", "artist": "Katy Perry"},
        {"name": "Born This Way", "artist": "Lady Gaga"},
        {"name": "Good as Hell", "artist": "Lizzo"},
        {"name": "Truth Hurts", "artist": "Lizzo"},
        {"name": "Driver's License", "artist": "Olivia Rodrigo"},
        {"name": "good 4 u", "artist": "Olivia Rodrigo"},
        {"name": "Shake It Off", "artist": "Taylor Swift"},
    ],
    "chaotic": [
        {"name": "Psychosocial", "artist": "Slipknot"},
        {"name": "Duality", "artist": "Slipknot"},
        {"name": "Panic Station", "artist": "Muse"},
        {"name": "Uprising", "artist": "Muse"},
        {"name": "Madness", "artist": "Muse"},
        {"name": "Hysteria", "artist": "Muse"},
        {"name": "Time Is Running Out", "artist": "Muse"},
        {"name": "Supermassive Black Hole", "artist": "Muse"},
        {"name": "Knights of Cydonia", "artist": "Muse"},
        {"name": "Chaos", "artist": "Mutemath"},
    ],
    "soft_acoustic": [
        {"name": "Bloom", "artist": "The Paper Kites"},
        {"name": "First Day of My Life", "artist": "Bright Eyes"},
        {"name": "Lua", "artist": "Bright Eyes"},
        {"name": "Old Pine", "artist": "Ben Howard"},
        {"name": "Keep Your Head Up", "artist": "Ben Howard"},
        {"name": "Turning Page", "artist": "Sleeping at Last"},
        {"name": "I Found", "artist": "Amber Run"},
        {"name": "Skinny Love", "artist": "Birdy"},
        {"name": "Fast Car", "artist": "Tracy Chapman"},
        {"name": "The Cave", "artist": "Mumford and Sons"},
    ],
    "indie": [
        {"name": "Ho Hey", "artist": "The Lumineers"},
        {"name": "Stubborn Love", "artist": "The Lumineers"},
        {"name": "Home", "artist": "Edward Sharpe and the Magnetic Zeros"},
        {"name": "Little Lion Man", "artist": "Mumford and Sons"},
        {"name": "The Cave", "artist": "Mumford and Sons"},
        {"name": "Dog Days Are Over", "artist": "Florence and the Machine"},
        {"name": "Lua", "artist": "Bright Eyes"},
        {"name": "Old Pine", "artist": "Ben Howard"},
        {"name": "Electric Feel", "artist": "MGMT"},
        {"name": "Stolen Dance", "artist": "Milky Chance"},
    ],
    "retro": [
        {"name": "Stayin Alive", "artist": "Bee Gees"},
        {"name": "Bohemian Rhapsody", "artist": "Queen"},
        {"name": "Hotel California", "artist": "Eagles"},
        {"name": "Roxanne", "artist": "The Police"},
        {"name": "Don't You Want Me", "artist": "Human League"},
        {"name": "Come On Eileen", "artist": "Dexys Midnight Runners"},
        {"name": "Take On Me", "artist": "a-ha"},
        {"name": "Girls Just Want to Have Fun", "artist": "Cyndi Lauper"},
        {"name": "Livin on a Prayer", "artist": "Bon Jovi"},
        {"name": "Sweet Home Alabama", "artist": "Lynyrd Skynyrd"},
    ],
    "fantasy": [
        {"name": "Harry Potter Theme", "artist": "John Williams"},
        {"name": "Lord of the Rings Theme", "artist": "Howard Shore"},
        {"name": "Somewhere Over the Rainbow", "artist": "Judy Garland"},
        {"name": "My Neighbor Totoro Theme", "artist": "Joe Hisaishi"},
        {"name": "Castle in the Sky Theme", "artist": "Joe Hisaishi"},
        {"name": "Spirited Away Theme", "artist": "Joe Hisaishi"},
        {"name": "A Whole New World", "artist": "Aladdin Soundtrack"},
        {"name": "Beauty and the Beast", "artist": "Celine Dion ft. Peabo Bryson"},
        {"name": "Can You Feel the Love Tonight", "artist": "Elton John"},
        {"name": "Circle of Life", "artist": "Elton John"},
    ],
    "adventurous": [
        {"name": "Born to Run", "artist": "Bruce Springsteen"},
        {"name": "Eye of the Tiger", "artist": "Survivor"},
        {"name": "Life Is a Highway", "artist": "Tom Cochrane"},
        {"name": "Africa", "artist": "Toto"},
        {"name": "Free Bird", "artist": "Lynyrd Skynyrd"},
        {"name": "Highway to Hell", "artist": "AC/DC"},
        {"name": "Thunderstruck", "artist": "AC/DC"},
        {"name": "On Top of the World", "artist": "Imagine Dragons"},
        {"name": "Radioactive", "artist": "Imagine Dragons"},
        {"name": "Adventure of a Lifetime", "artist": "Coldplay"},
    ],
    "triumphant": [
        {"name": "We Are the Champions", "artist": "Queen"},
        {"name": "Eye of the Tiger", "artist": "Survivor"},
        {"name": "Victorious", "artist": "Panic at the Disco"},
        {"name": "Champion", "artist": "Fall Out Boy"},
        {"name": "Kings and Queens", "artist": "Ava Max"},
        {"name": "Thunder", "artist": "Imagine Dragons"},
        {"name": "On Top of the World", "artist": "Imagine Dragons"},
        {"name": "Started From the Bottom", "artist": "Drake"},
        {"name": "HUMBLE", "artist": "Kendrick Lamar"},
        {"name": "Till I Collapse", "artist": "Eminem"},
    ],
}


def get_custom_songs(mood_label: str) -> list:
    mood_lower = mood_label.lower().replace(" ", "_").replace("-", "_")
    if mood_lower in MOOD_SONGS:
        return MOOD_SONGS[mood_lower]
    for key in MOOD_SONGS:
        if key in mood_lower or mood_lower in key:
            return MOOD_SONGS[key]
    return []
